### ISSUE TITLE
Compatibility with Indigo 2022.1

### ISSUE THREAD

**Issue by indynz** [kmarkley/Indigo-Timed-Devices#2]
Hi.

Thanks for your effort on creating the plugin. I find it quite useful!

However, After upgrading to Indigo 2022.1 the plugin does not seem to work as expected. 

When adding a new timer, the states dropdown does not populate like it used to earlier.

![2022-06-20_10-36-40](https://user-images.githubusercontent.com/161815/174502879-bc2077d7-1e6a-4039-9753-42f2f1ef6d52.png)

Are you thinking of upgrading the plugin so it works with the latest version of Indigo.

Thanks.

**Comment by kmarkley** [comment]
After selecting the device(s), click the "Load Device States" button to load device states so you can select them
